### PR TITLE
Handle recent changes to ggplot2's `plot_build()` logic

### LINKED ISSUE #2259: Error in match.fun(FUN): 'ggfun("scales_transform_df")' is not a function, character or symbol
FYI, future changes in `ggplot2` will break `ggplotly()`. The following example did not work with the development version of `ggplot2`.
See also this [discussion](https://github.com/tidyverse/ggplot2/issues/5285#issuecomment-1522089382) 
``` r
library(dplyr)
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.4.2.9000'

data("airquality")

airquality <- airquality %>% 
  select(Month, Day, Temp) %>% 
  mutate(Date = as.Date(paste("1973", Month, Day, sep = "-")))

plt1 <- ggplot(airquality,
               aes(x = Date,
                   y = Temp)) +
  geom_line() +
  theme_bw()
```

``` r

library(plotly)
packageVersion("plotly")
#> [1] '4.10.1'

ggplotly(plt1, 
         tooltip = c("x", "y", "color", "text"),
         dynamicTicks = TRUE) %>% 
  rangeslider() %>%
  layout(
    legend = list(orientation = "h", x = 0.1, y = -0.5)
  )
#> Error in match.fun(FUN): 'ggfun("scales_transform_df")' is not a function, character or symbol
```

https://github.com/plotly/plotly.R/blob/master/R/ggplotly.R#L317

```
# Transform all scales
data <- lapply(data, ggfun("scales_transform_df"), scales = scales)
```

https://github.com/plotly/plotly.R/blob/master/R/ggplotly.R#L1391-L1395

```
# We need access to internal ggplot2 functions in several places
# this helps us import functions in a way that R CMD check won't cry about
ggfun <- function(x) {
  tryCatch(getFromNamespace(x, "ggplot2"), error = function(e) NULL)
}
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #2259

This PR add support for recent (internal) changes to ggplot2 (mostly the ones made in https://github.com/tidyverse/ggplot2/pull/4879 and https://github.com/tidyverse/ggplot2/pull/5144).  These changes removed some internal ggplot2 functions `ggplotly()` was using to translate to plotly.js. Fortunately, the relevant logic is still accessible via methods on the plot object, so going forward `ggplotly()` won't be as reliant on internal ggplot2 functions.

### CODE REVIEW

File: R/ggplotly.R [hunk 1]
```diff
@@ -1459,3 +1459,36 @@ getAesMap <- function(plot, layer) {
...
+scales_map_df <- function(scales, df) {
+  if (is.function(scales$map_df)) {
+    scales$map_df(df)
+  } else {
+    ggfun("scales_map_df")(df, scales = scales)
+  }
+}
+
+scales_add_missing <- function(plot, aesthetics) {
+  if (length(plot$scales$add_missing)) {
```
Comment (cpsievert) [inline R/ggplotly.R:1489]:
```suggestion
  if (is.function(plot$scales$add_missing)) {
```

File: R/ggplotly.R [hunk 2]
```diff
@@ -1459,3 +1459,36 @@ getAesMap <- function(plot, layer) {
     layer$mapping
   }
 }
+
+# Handle compatibility for changes in ggplot2 >v3.4.2 (#5144)
```
Comment (cpsievert) [inline R/ggplotly.R:1463]:
```suggestion
# ------------------------------------------------------------------
# Handle compatibility for changes in ggplot2 >v3.4.2 (#5144),
# which removed these functions in favor of scale/plot methods
# ------------------------------------------------------------------
```
