### PR TITLE
Accommodate breaking changes in ggplot2 3.4.0

### LINKED ISSUE #2193: Issues with next version of ggplot2
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are due to our switch to using the `linewidth` aesthetic for stroke width instead of `size`. Please see https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/ for more info on this.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

### PR DESCRIPTION
**Pull request by cpsievert**
Close #2193

### CODE REVIEW

File: R/layers2traces.R [hunk 1]
```diff
@@ -697,6 +706,10 @@ geom2trace.GeomBlank <- function(data, params, p) {
 #' @export
 geom2trace.GeomPath <- function(data, params, p) {
   data <- group2NA(data)
+  
+  # ggplot2 >3.4.0 changed from size to linewidth for controlling line width
+  width_var <- if ("linewidth" %in% names(data)) "linewidth" else "size"
```
Comment (cpsievert) [inline R/layers2traces.R:711]: Consider pulling this logic out into a reusable function
